[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "vibelint"
version = "0.1.2"
description = "Suite of tools to enhance the vibe coding process."
authors = [
  { name = "Mithran Mohanraj", email = "mithran.mohanraj@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Quality Assurance",
]
dependencies = [
    "click>=8.1.0",
    "tomli>=2.0.0; python_version < '3.11'",
    "tomli-w",
    "colorama>=0.4.0",
    "rich>=12.0.0",
    "libcst",
    "requests>=2.25.0",
    "langchain>=0.3.0",
    "langchain-openai>=0.3.0",
    "langchain-core>=0.3.0"
]

[project.optional-dependencies]
embedding = [
    "sentence-transformers>=2.2.0",
    "torch>=1.9.0",
    "numpy>=1.21.0"
]

[project.scripts]
vibelint = "vibelint.cli:main"

[project.entry-points."vibelint.validators"]
# New semantic rule IDs (preferred) - now pointing to individual files
"DOCSTRING-MISSING" = "vibelint.validators.docstring:MissingDocstringValidator"
"DOCSTRING-PATH-REFERENCE" = "vibelint.validators.docstring:DocstringPathValidator"
"EXPORTS-MISSING-ALL" = "vibelint.validators.exports:MissingAllValidator"
"EXPORTS-MISSING-ALL-INIT" = "vibelint.validators.exports:InitAllValidator"
"PRINT-STATEMENT" = "vibelint.validators.print_statements:PrintStatementValidator"
"EMOJI-IN-STRING" = "vibelint.validators.emoji:EmojiUsageValidator"
"DEAD-CODE-FOUND" = "vibelint.validators.dead_code:DeadCodeValidator"
"ARCHITECTURE-INCONSISTENT" = "vibelint.validators.architecture.basic_patterns:ArchitectureValidator"
"TYPING-POOR-PRACTICE" = "vibelint.validators.typing_quality:TypingQualityValidator"
"ARCHITECTURE-LLM" = "vibelint.validators.architecture.llm_analysis:LLMAnalysisValidator"
"SEMANTIC-SIMILARITY" = "vibelint.validators.architecture.semantic_similarity:SemanticSimilarityValidator"
"FALLBACK-SILENT-FAILURE" = "vibelint.validators.architecture.fallback_patterns:FallbackAnalyzer"


[project.entry-points."vibelint.formatters"]
human = "vibelint.formatters:HumanFormatter"
natural = "vibelint.formatters:NaturalLanguageFormatter"
json = "vibelint.formatters:JsonFormatter"
sarif = "vibelint.formatters:SarifFormatter"
llm = "vibelint.formatters:LLMFormatter"

[project.urls]
"Homepage" = "https://github.com/mithranm/vibelint"
"Bug Tracker" = "https://github.com/mithranm/vibelint/issues"

[tool.setuptools.packages.find]
where = ["src"]
include = ["vibelint*"]

[tool.vibelint]
# Simple configuration - most users just need this
include_globs = ["src/**/*.py", "tests/**/*.py"]
exclude_globs = ["tests/fixtures/*"]

# Rule severity levels: "OFF", "INFO", "WARN", "BLOCK"
[tool.vibelint.rules]
"PRINT-STATEMENT" = "WARN"
"EMOJI-IN-STRING" = "WARN" 
"DEAD-CODE-FOUND" = "INFO"
"ARCHITECTURE-LLM" = "WARN"

# LLM configuration (required for AI analysis)
[tool.vibelint.llm_analysis]
api_base_url = "http://100.94.250.88:11434"
model = "/home/mithranmohanraj/models/gpt-oss-20b-mxfp4.gguf"
temperature = 0.1
max_tokens = 4096

[tool.black]
target-version = ["py310", "py311", "py312"]
line-length=100

[tool.ruff]
line-length = 100
target-version = "py310"
exclude = [
    ".git",
    ".pytest_cache",
    "__pycache__",
    "build",
    "dist",
    ".venv",
    "venv"
]

[tool.ruff.lint]
select = [
    "E",      # pycodestyle errors
    "W",      # pycodestyle warnings
    "F",      # pyflakes
]
ignore = [
    "E501",   # Line too long (handled by black)
    "B008",   # Allow function calls in argument defaults
    "B904",   # Allow raise without from for now
    "UP036",  # Allow outdated version blocks
    "C414",   # Allow unnecessary list() calls for clarity
    "SIM102", # Allow nested if statements
    "SIM210", # Allow if-else instead of bool()
    "SIM113", # Allow manual index tracking
    "SIM103", # Allow explicit return True/False
    "N802",   # Allow uppercase function names (LibCST visitor methods)
    "N806",   # Allow uppercase variables
    "B006",   # Allow mutable defaults for now
    "B007",   # Allow unused loop variables
    "UP007",  # Allow Union syntax for now
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["F401", "F811"]  # Allow unused imports in tests

[tool.setuptools.package-data]
vibelint = ["VIBECHECKER.txt"]