[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "vibelint"
description = "A linting tool to make Python codebases more LLM-friendly"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Quality Assurance",
]
dependencies = [
    "click>=8.1.0",
    "tomli>=2.0.0; python_version < '3.11'",
    "colorama>=0.4.0",
    "rich>=12.0.0",
]
dynamic = ["version"]

[project.scripts]
vibelint = "vibelint.cli:main"

[project.urls]
"Homepage" = "https://github.com/mithranm/vibelint"
"Bug Tracker" = "https://github.com/mithranm/vibelint/issues"

[tool.setuptools.packages.find]
where = ["src"]
include = ["vibelint*"]

[tool.setuptools_scm]
write_to = "vibelint/_version.py"

[tool.vibelint]
package_root = ""
allowed_shebangs = ["#!/usr/bin/env python3"]
docstring_regex = "^[A-Z].+\\.$"
include_globs = ["**/*.py"]
exclude_globs = ["**/tests/**", "**/migrations/**", "**/site-packages/**", "**/dist-packages/**"]
large_dir_threshold = 500